account_id = "acct_id_hex"
kv_namespaces = [{binding = "KV", id = "kv_id_hex"}]
name = "hosymbot-worker"
route = ""
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = true
zone_id = ""
