account_id = "acct_id_hex"
kv_namespaces = [{binding = "KV", id = "kv_id_hex"}]
name = "hosymbot-worker"
route = ""
type = "webpack"
vars = {BOT_TOKEN = "botid:botkey", DOMAIN = "hosymbot-worker.endpoint.workers.dev", WHITELISTED_HOSTNAMES = "asset.storage.example.com|another.asset.storage.example.com", META_URL = "https://example.com/meta/json/path/meta.json"}
workers_dev = true
zone_id = ""
